Repository saleor/storefront, pull requests merged in 2021-11, with the labels that each got.

#60 Fix register account redirect url
  pages/account/register.tsx
Labels: Stale

#66 update deps
  package.json
  pnpm-lock.yaml
Labels: created-by: Saleor team

#65 Search page
  components/Navbar.tsx
  package.json
  pages/search.tsx
  pnpm-lock.yaml
Labels: Stale, created-by: Saleor team

#68 Product variant images
  graphql.schema.json
  graphql/queries.graphql
  pages/products/[slug].tsx
  saleor/api.tsx
Labels: Stale

#69 Layout implementation
  components/AccountLayout.tsx
  components/BaseTemplate.tsx
  components/Layout.tsx
  components/index.ts
  pages/[sitemap]/index.tsx
  pages/_app.tsx
  pages/account/addressBook.tsx
  pages/account/orders.tsx
  pages/account/orders/[token].tsx
  pages/account/preferences.tsx
  pages/cart.tsx
  pages/category/[slug].tsx
  pages/checkout.tsx
  pages/collection/[slug].tsx
  pages/index.tsx
  pages/order.tsx
  pages/page/[slug].tsx
  pages/products/[slug].tsx
  pages/search.tsx
Labels: Stale
